version: "3.9"
x-logging:
  &x-logging
  options:
    max-size: 50m
    max-file: "1"
  driver: json-file
x-restart: &x-restart "unless-stopped"
x-stop-grace-period: &x-stop-grace-period "3s"

services:
  ros2-data-collection:
    image: ghcr.io/minipada/ros2_data_collection:humble-source-sim
    privileged: true
    container_name: ros2-data-collection
    environment:
      - QT_X11_NO_MITSHM=1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,display
      - DISPLAY=unix$DISPLAY
      - XAUTHORITY=$XAUTHORITY
    volumes:
      - ${HOME}/.Xauthority:/root/.Xauthority
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}:/root/ws/src/ros2_data_collection
    network_mode: "host"
    logging: *x-logging
    restart: *x-restart
    stop_grace_period: *x-stop-grace-period
    runtime: nvidia
    command: tail -F anything
    working_dir: /root/ws
