destination_server:
  ros__parameters:
    flb:
      flush: 1
      flb_grace: 1
      log_level: "info"
      storage_path: "/var/log/flb-storage/"
      storage_sync: "full"
      storage_checksum: "off"
      storage_backlog_mem_limit: "1M"
      scheduler_cap: 200
      scheduler_base: 5
      http_server: true
      http_listen: "0.0.0.0"
      http_port: 2020
      in_storage_type: "filesystem"
      in_storage_pause_on_chunks_overlimit: "off"
    destination_plugins: ["flb_stdout"]
    custom_str_params_list: ["robot_name", "id"]
    run_id:
      enabled: false
    flb_stdout:
      plugin: "dc_destinations/Flbstdout"
      inputs: ["/dc/measurement/custom"]
      time_format: "double"
      time_key: "date"
      debug: false

measurement_server:
  ros__parameters:
    measurement_plugins: ["custom"]
    condition_plugins: ["same_a"]
    same_a:
      plugin: "dc_conditions/SameAsPrevious"
      topic: "/dc/measurement/custom"
      paths: ["a"]
    custom:
      plugin: "dc_measurements/Uptime"
      group_key: "custom"
      topic_output: "/dc/measurement/custom"
      polling_interval: 1000
      enable_validator: false
      tags: ["flb_stdout"]
      init_collect: true
      if_none_conditions: ["same_a"]
