version: '3.1'

services:
  db:
    image: postgres:13
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: dc
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
