{
 "title": "ROS 2 Data Collection - System",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "run_id",
    "label": "Run ID",
    "query": "SELECT \"run_id\" FROM \"autogen\".\"flb_influxdb\""
   },
   {
    "name": "robot_name",
    "label": "Robot Name",
    "query": "SELECT \"robot_name\" FROM \"autogen\".\"flb_influxdb\""
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 20, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<img id=\"logo-dc\"\n    style=\"max-width: 150px; width: 60%; margin-left: auto; margin-right: auto; display: block; margin-bottom: 3px;\"\n    src=\"/public/img/dc/dc.png\">\n\n<h4><a href=\"http://localhost:3000/\">Home</a></h4>\n<h4><a href=\"http://localhost:3000/d/bfb348f2-c2cb-47c3-a3d1-dcc26a204f05/ros-2-data-collection-system\">System</a></h4>\n<h4><a href=\"http://localhost:3000/d/e5e1e5c0-c76e-4545-ad8e-8747ee3f09b8/ros-2-data-collection-robot\">Robot</a></h4>\n<h4><a href=\"http://localhost:3000/d/bcd48967-2d49-4c3d-8091-ce6e71a8b009/ros-2-data-collection-environment\">Environment</a></h4>\n<h4><a href=\"http://localhost:3000/d/ed559b23-bbc2-4b45-a58e-24566881b970/ros-2-data-collection-infrastructure\">Infrastructure</a></h4>\n\n<p><strong>Documentation</strong>: <a\n        href=\"https://minipada.github.io/ros2_data_collection\">https://minipada.github.io/ros2_data_collection</a></p>\n<p><strong>Source code</strong>: <a\n        href=\"https://github.com/minipada/ros2_data_collection\">https://github.com/minipada/ros2_data_collection</a></p>\n\n<div>Under <a target=\"_blank\" s href=\"https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2)\">MPL-2.0</a>\n    license</a>\n</div>\n"
   }
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "flb_influxdb",
     "query": "SELECT \"date\" FROM \"autogen\".\"flb_influxdb\" WHERE $timeFilter ORDER BY ASC LIMIT 1",
     "select": [
      [
       { "params": [ "date" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run_id::field", "operator": "=~", "value": "/^$run_id$/" },
      { "condition": "AND", "key": "robot_name::field", "operator": "=~", "value": "/^$robot_name$/" }
     ]
    }
   ]
  },
  {
   "title": "End time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "limit": "1",
     "measurement": "flb_influxdb",
     "query": "SELECT \"date\" FROM \"autogen\".\"flb_influxdb\" WHERE $timeFilter ORDER BY DESC LIMIT 1",
     "select": [
      [
       { "params": [ "date" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run_id::field", "operator": "=~", "value": "/^$run_id$/" },
      { "condition": "AND", "key": "robot_name::field", "operator": "=~", "value": "/^$robot_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "flb_influxdb",
     "select": [
      [
       { "params": [ "/uptime/time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "run_id::field", "operator": "=~", "value": "/^$run_id$/" },
      { "condition": "AND", "key": "robot_name::field", "operator": "=~", "value": "/^$robot_name$/" }
     ]
    }
   ]
  },
  {
   "title": "OS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "flb_influxdb",
     "query": "SELECT last(\"/os/os\") FROM \"autogen\".\"flb_influxdb\" WHERE $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "/os/os" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "run_id::field", "operator": "=~", "value": "/^$run_id$/" },
      { "condition": "AND", "key": "robot_name::field", "operator": "=~", "value": "/^$robot_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 14, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "flb_influxdb",
     "select": [
      [
       { "params": [ "/os/kernel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "run_id::field", "operator": "=~", "value": "/^$run_id$/" },
      { "condition": "AND", "key": "robot_name::field", "operator": "=~", "value": "/^$robot_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory (Gb)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flb_influxdb",
     "select": [
      [
       { "params": [ "/os/memory" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "run_id::field", "operator": "=~", "value": "/^$run_id$/" },
      { "condition": "AND", "key": "robot_name::field", "operator": "=~", "value": "/^$robot_name$/" }
     ]
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flb_influxdb",
     "select": [
      [
       { "params": [ "/os/cpus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "run_id::field", "operator": "=~", "value": "/^$run_id$/" },
      { "condition": "AND", "key": "robot_name::field", "operator": "=~", "value": "/^$robot_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 6 },
   "targets": [
    {
     "measurement": "flb_influxdb",
     "select": [
      [
       { "params": [ "/memory/used" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "run_id::field", "operator": "=~", "value": "/^$run_id$/" },
      { "condition": "AND", "key": "robot_name::field", "operator": "=~", "value": "/^$robot_name$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 6 },
   "targets": [
    {
     "alias": "Average CPU",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flb_influxdb",
     "select": [
      [
       { "params": [ "/cpu/average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "run_id::field", "operator": "=~", "value": "/^$run_id$/" },
      { "condition": "AND", "key": "robot_name::field", "operator": "=~", "value": "/^$robot_name$/" }
     ]
    },
    {
     "alias": "Processes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "flb_influxdb",
     "select": [
      [
       { "params": [ "/cpu/processes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}