destination_server:
  ros__parameters:
    flb:
      flush: 1
      flb_grace: 1
      log_level: "info"
      storage_path: "/var/log/flb-storage/"
      storage_sync: "full"
      storage_checksum: "off"
      storage_backlog_mem_limit: "1M"
      scheduler_cap: 200
      scheduler_base: 5
      http_server: true
      http_listen: "0.0.0.0"
      http_port: 2020
      in_storage_type: "filesystem"
      in_storage_pause_on_chunks_overlimit: "off"
    destination_plugins: ["flb_minio", "flb_pgsql", "flb_files_metrics"]
    custom_str_params_list: ["robot_name", "id"]
    custom_str_params:
      robot_name:
        name: robot_name
        value: "C3PO"
      # Requires systemd package
      id:
        name: id
        value_from_file: /etc/machine-id
    flb_files_metrics:
      plugin: "dc_destinations/FlbFilesMetrics"
      inputs:
        [
          "/dc/measurement/map",
          "/dc/measurement/right_camera",
          "/dc/measurement/left_camera",
        ]
      file_storage: ["minio"]
      db_type: "pgsql"
      delete_when_sent: true
      minio:
        endpoint: 127.0.0.1:9000
        access_key_id: rQXPf1f730Yuu2yW
        secret_access_key: TYYkjN5L4gqDgCGLzQahHDcvqL4WNTcb
        use_ssl: false
        bucket: "mybucket"
        src_fields:
          [
            "local_paths.pgm",
            "local_paths.yaml",
            "local_paths.inspected",
            "local_paths.inspected",
          ]
        upload_fields:
          [
            "remote_paths.minio.pgm",
            "remote_paths.minio.yaml",
            "remote_paths.minio.inspected",
            "remote_paths.minio.inspected",
          ]
      pgsql:
        host: "127.0.0.1"
        port: "5432"
        user: fluentbit
        password: password
        database: "fluentbit"
        table: "files_metrics"
        timestamp_key: "date"
        time_format: "double"
        time_key: "date"
        ssl: false
    flb_minio:
      verbose_plugin: false
      time_format: "iso8601"
      plugin: "dc_destinations/FlbMinIO"
      inputs: ["/dc/measurement/right_camera", "/dc/measurement/left_camera"]
      endpoint: 127.0.0.1:9000
      access_key_id: rQXPf1f730Yuu2yW
      secret_access_key: TYYkjN5L4gqDgCGLzQahHDcvqL4WNTcb
      use_ssl: false
      bucket: "mybucket"
      src_fields:
        [
          "local_paths.pgm",
          "local_paths.yaml",
          "local_paths.inspected",
          "local_paths.inspected",
        ]
      upload_fields:
        [
          "remote_paths.minio.pgm",
          "remote_paths.minio.yaml",
          "remote_paths.minio.inspected",
          "remote_paths.minio.inspected",
        ]
    flb_pgsql:
      plugin: "dc_destinations/FlbPgSQL"
      inputs:
        [
          "/dc/measurement/map",
          "/dc/measurement/right_camera",
          "/dc/measurement/left_camera",
          "/dc/group/robot",
        ]
      host: "127.0.0.1"
      port: 5432
      user: fluentbit
      password: password
      database: "fluentbit"
      table: "dc"
      timestamp_key: "date"
      async: false
      time_format: "double"
      time_key: "date"

group_server:
  ros__parameters:
    groups: ["robot"]
    robot:
      inputs:
        [
          "/dc/measurement/cmd_vel",
          "/dc/measurement/position",
          "/dc/measurement/speed",
        ]
      output: "/dc/group/robot"
      sync_delay: 5.0
      group_key: "robot"
      tags: ["flb_pgsql"]

measurement_server:
  ros__parameters:
    custom_str_params: ["robot_name"]
    robot_name: "C3PO"
    measurement_plugins: ["cmd_vel", "position", "speed", "map", "right_camera"]
    run_id:
      enabled: true
      counter: true
      counter_path: "$HOME/run_id"
      uuid: false
    save_local_base_path: "$HOME/dc_data/"
    all_base_path: "=robot_name/%Y/%m/%d/%H"
    condition_plugins: ["moving", "inspected_exists"]
    destinations:
      minio:
        bucket: mybucket
    moving:
      plugin: "dc_conditions/Moving"
    inspected_exists:
      plugin: "dc_conditions/Exist"
      key: "inspected"
    cmd_vel:
      plugin: "dc_measurements/CmdVel"
      group_key: "cmd_vel"
      enable_validator: true
      topic_output: "/dc/measurement/cmd_vel"
      include_measurement_name: true
    position:
      plugin: "dc_measurements/Position"
      group_key: "position"
      topic_output: "/dc/measurement/position"
      enable_validator: true
      init_collect: true
      global_frame: "map"
      robot_base_frame: "base_link"
      transform_timeout: 0.1
      include_measurement_name: true
    speed:
      plugin: "dc_measurements/Speed"
      group_key: "speed"
      odom_topic: "/odom"
      topic_output: "/dc/measurement/speed"
      include_measurement_name: true
    map:
      plugin: "dc_measurements/Map"
      group_key: "map"
      polling_interval: 30000
      save_path: "map/%Y-%m-%dT%H-%M-%S"
      topic_output: "/dc/measurement/map"
      save_map_timeout: 4.0
      init_collect: true
      remote_prefixes: [""]
      remote_keys: ["minio"]
      enable_validator: true
      tags: ["flb_pgsql", "flb_minio", "flb_files_metrics"]
      include_measurement_name: true
      quiet: true
    right_camera:
      plugin: "dc_measurements/Camera"
      group_key: "right_camera"
      if_none_conditions: ["moving"]
      if_all_conditions: ["inspected_exists"]
      topic_output: "/dc/measurement/right_camera"
      init_collect: false
      init_max_measurements: -1
      condition_max_measurements: 1
      node_name: "dc_measurement_camera"
      cam_topic: "/right_intel_realsense_r200_depth/image_raw"
      cam_name: right_camera
      enable_validator: true
      draw_det_barcodes: true
      save_raw_img: false
      save_rotated_img: false
      save_detections_img: true
      save_inspected_path: "right_camera/inspected/%Y-%m-%dT%H-%M-%S"
      rotation_angle: 0
      detection_modules: ["barcode"]
      remote_prefixes: [""]
      remote_keys: ["minio"]
      tags: ["flb_pgsql", "flb_minio", "flb_files_metrics"]
      include_measurement_name: true
    left_camera:
      plugin: "dc_measurements/Camera"
      group_key: "left_camera"
      if_none_conditions: ["moving"]
      if_all_conditions: ["inspected_exists"]
      topic_output: "/dc/measurement/left_camera"
      init_collect: true
      init_max_measurements: -1
      condition_max_measurements: 1
      node_name: "dc_measurement_camera"
      cam_topic: "/left_intel_realsense_r200_depth/image_raw"
      cam_name: left_camera
      enable_validator: true
      draw_det_barcodes: true
      save_raw_img: false
      save_rotated_img: false
      save_detections_img: true
      save_inspected_path: "left_camera/inspected/%Y-%m-%dT%H-%M-%S"
      rotation_angle: 0
      detection_modules: ["barcode"]
      remote_prefixes: [""]
      remote_keys: ["minio"]
      tags: ["flb_pgsql", "flb_minio", "flb_files_metrics"]
      include_measurement_name: true
