destination_server:
  ros__parameters:
    destination_plugins: ["flb_stdout"]
    flb_stdout:
      plugin: "dc_destinations/Flbstdout"
      inputs: ["/dc/measurement/uptime"]

measurement_server:
  ros__parameters:
    measurement_plugins: ["uptime"]
    uptime:
      plugin: "dc_measurements/Uptime"
      group_key: "uptime"
      topic_output: "/dc/measurement/uptime"
      polling_interval: 5000
      enable_validator: true
      debug: true
      tags: ["flb_stdout"]
