destination_server:
  ros__parameters:
    flb:
      flush: 1
      flb_grace: 1
      log_level: "info"
      storage_path: "/var/log/flb-storage/"
      storage_sync: "full"
      storage_checksum: "off"
      storage_backlog_mem_limit: "1M"
      scheduler_cap: 200
      scheduler_base: 5
      http_server: true
      http_listen: "0.0.0.0"
      http_port: 2020
      in_storage_type: "filesystem"
      in_storage_pause_on_chunks_overlimit: "off"
    destination_plugins: ["flb_stdout"]
    run_id:
      enabled: false
    flb_stdout:
      plugin: "dc_destinations/FlbStdout"
      inputs: ["/dc/measurement/uptime_custom"]
      time_format: "double"
      time_key: "date"
      debug: false

measurement_server:
  ros__parameters:
    measurement_plugins: ["uptime_custom"]
    uptime_custom:
      plugin: "dc_demos/UptimeCustom"
      group_key: "uptime"
      topic_output: "/dc/measurement/uptime_custom"
      polling_interval: 5000
      enable_validator: true
      tags: ["flb_stdout"]
      init_collect: true
