apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: db:5432
    database: dc
    user: dc
    secureJsonData:
      password: password
    jsonData:
      sslmode: disable
      postgresVersion: 1300
    isDefault: true
    uid: dc_postgres
