; SPDX-FileCopyrightText: 2022-2026 David Bensoussan
;
; SPDX-License-Identifier: MPL-2.0

instance_name = "ROS 2 Data Collection"
app_mode = development

[dashboards]
default_home_dashboard_path = "/etc/dashboards/home.json"

[panels]
disable_sanitize_html = true
