name: Documentation

on:
  push:
    branches:
      - humble

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: .

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: "latest"

      - run: cargo install mdbook-open-on-gh mdbook mdbook-admonish mdbook-linkcheck mdbook-mermaid

      - run: mdbook build
        working-directory: doc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/book/html
