name: Documentation

on:
  push:
    branches:
      - humble
    paths:
      - doc/**
      - .github/workflows/doc.yaml
  pull_request:
    paths:
      - doc/**
      - .github/workflows/doc.yaml

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-22.04
    container:
      image: minipada/ros2_data_collection:humble-doc
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: .
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"
      - name: Install Python dependencies (dev)
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements-dev.txt"
      - name: Generate strictdoc pages
        run: |
          strictdoc export requirements --experimental-enable-file-traceability --enable-mathjax --format=html --output-dir doc/src/dc/requirements --project-title "ROS 2 Data Collection"
      - name: Build documentation
        working-directory: ./doc
        run: mdbook build
      - name: Deploy
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/book/html
